// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ftpkflwtoxedulzyswuh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0cGtmbHd0b3hlZHVsenlzd3VoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NDM1MTYsImV4cCI6MjA2MDAxOTUxNn0.0j5gojKDpCrbOEWi3FMOgGdHQ3Gl-rkS-I_dwpuiDAg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);